### ISSUE TITLE
Plugfest example credentials issuer/VM mismatch

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-ed#30]
In these two examples, the issuer id does not match the DID in the verification method used to sign the proof:
https://github.com/w3c-ccg/vc-ed/blob/62fd85ef270e2654b6b69f82d8a5a6d12680f19b/plugfest-1-2022/plugfest-1-ex-1.json
https://github.com/w3c-ccg/vc-ed/blob/62fd85ef270e2654b6b69f82d8a5a6d12680f19b/plugfest-1-2022/plugfest-1-ex-2.json

The VCs have issuer id `did:key:z6Mkv8wY2XpNF48tFHomipRnh6eBNT1H7YB53yLNK2NSJKmH`...
https://github.com/w3c-ccg/vc-ed/blob/62fd85ef270e2654b6b69f82d8a5a6d12680f19b/plugfest-1-2022/plugfest-1-ex-1.json#L10-L12
https://github.com/w3c-ccg/vc-ed/blob/62fd85ef270e2654b6b69f82d8a5a6d12680f19b/plugfest-1-2022/plugfest-1-ex-2.json#L10-L12

... while their proofs' verification methods use `did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn`:
https://github.com/w3c-ccg/vc-ed/blob/62fd85ef270e2654b6b69f82d8a5a6d12680f19b/plugfest-1-2022/plugfest-1-ex-1.json#L29-L32
https://github.com/w3c-ccg/vc-ed/blob/62fd85ef270e2654b6b69f82d8a5a6d12680f19b/plugfest-1-2022/plugfest-1-ex-2.json#L32-L35

Is this intentional - and there is some externally-known relationship between the issuer and the verification method controller? Or should the examples be updated to use the same key/DID for the proof/signature as for the issuer id?

**Comment by kayaelle** [comment]
Thanks for bringing this up. Will look into it and follow up.

**Comment by kayaelle** [comment]
I signed with the wrong DID. I resigned and updated the landing page and examples. It should be ok now. Thanks for pointing that out!

**Comment by clehner** [comment]
Cool! I see the issuers match the verification methods now. I can verify the updated `plugfest-1-ex-1.json` (https://github.com/w3c-ccg/vc-ed/blob/11722cbcb59e5ad4f90f8f74a2ff9fc4da426d0a/plugfest-1-2022/plugfest-1-ex-1.json).
