### ISSUE TITLE
Unable to verify second Open Badge example VC

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-ed#32]
I successfully verify the first Plugfest example credential (`plugfest-1-ex-1.json` "Open Badge 3.0 with Badge Image & Required Fields")
https://github.com/kayaelle/vc-ed/blob/94ba7bc657e3d249ce09fdf94d3b1d9045e253db/plugfest-1-2022/index.md#open-badge-30-with-badge-image--required-fields
https://github.com/kayaelle/vc-ed/blob/94ba7bc657e3d249ce09fdf94d3b1d9045e253db/plugfest-1-2022/plugfest-1-ex-1.json
https://w3c-ccg.github.io/vc-ed/plugfest-1-2022/plugfest-1-ex-1.json

... but I'm unable to verify signature/proof on the second one (`plugfest-1-ex-2.json` "Open Badge 3.0 with Optional & Required Fields")
https://github.com/kayaelle/vc-ed/blob/94ba7bc657e3d249ce09fdf94d3b1d9045e253db/plugfest-1-2022/index.md#open-badge-30-with-optional--required-fields
https://github.com/w3c-ccg/vc-ed/blob/94ba7bc657e3d249ce09fdf94d3b1d9045e253db/plugfest-1-2022/plugfest-1-ex-2.json
https://w3c-ccg.github.io/vc-ed/plugfest-1-2022/plugfest-1-ex-2.json

I am seeing this with multiple verifier implementations.

**Comment by dmitrizagidulin** [comment]
@clehner - thanks for the heads up, we'll take a look!

**Comment by kayaelle** [comment]
Hi @clehner - I updated the example file and the plugfest landing page where it shows that example. Not sure what happened with the other example. I could have pasted in wrong. 

Thanks!

**Comment by clehner** [comment]
I successfully verify the updated `plugfest-1-ex-2.json` in 7e343665f32437fb43c6c0288405aefdbe5ba4fe!
